### ISSUE TITLE
High-level question

### ISSUE THREAD

**Issue by MichaelCurrie** [JimHokanson/turtle_json#6]
I haven't read nearly anything yet, so this will be naive.

But is the idea you will:
1. Merge https://github.com/JimHokanson/tracker-commons into https://github.com/OpenWorm/tracker-commons
2. Have the Matlab part of tracker-commons import https://github.com/JimHokanson/turtle_json ?

If so, how will turtle_json be distributed?  Just from the github repo, or via some kind of packaging (like the [Matlab Central File Exchange](https://www.mathworks.com/matlabcentral/fileexchange/?requestedDomain=www.mathworks.com)?

Thanks

**Comment by JimHokanson** [comment]
1) Yes. Merging will be done by the end of this weekend.
2) Turtle-JSON will be a requirement. How best to require this is unclear, but possible via a "Matlab app" Most likely Turtle-JSON, when ready, will go on the File Exchange as well.
